version: 2

models:
  - name: annoying-puzzle-event_flatten_raw
    description: "Bảng dữ liệu Game Mobile đã được làm phẳng"
    columns:
      - name: surrogate_key
        tests:
          - unique
          - not_null
      - name: event_date
        tests:
          - not_null